using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Tekla.Structures.Model;
using Tekla.Structures.Model.UI;

namespace RebarPhasesManager.Model
{
    public static class RebarVisualizator
    {
        //public static void SetTempColor(List<model)
        //{
        //    foreach (PhaseItem phaseItem in phaseItemList)
        //    {
        //        if (phaseItem.Visible)
        //        {
        //            List<ModelObject> modelObjects = new List<ModelObject>();
        //            foreach (Reinforcement rf in phaseItem.RebarsList)
        //            {
        //                modelObjects.Add(rf);
        //            }
        //            ModelObjectVisualization.SetTemporaryState(modelObjects, phaseItem.TeklaColor);
        //        }
        //        else
        //        {
        //            List<ModelObject> modelObjects = new List<ModelObject>();
        //            foreach (Reinforcement rf in phaseItem.RebarsList)
        //            {
        //                modelObjects.Add(rf);
        //            }
        //            ModelObjectVisualization.SetTemporaryState(modelObjects, new Color(0.5, 0.5, 0.5));
        //        }
        //    }
        //}
    }
}
